name: open_textview
description: Open Source TextViewer.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.9+239

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  ionicons: ^0.1.2
  get: ^4.6.3
  audio_service: ^0.18.4
  audio_session: ^0.1.6+1
  file_picker: ^4.5.0
  url_launcher:
  flutter_tts: ^3.2.2
  flutter_charset_detector: ^1.0.2
  charset_converter: ^2.1.0
  intl: ^0.17.0 
  path_provider: ^2.0.1
  
  flutter_slidable: ^1.2.1
  wakelock: ^0.5.6
  image: 
  

  
  
 
  package_info: ^2.0.2
  share_plus: ^2.0.4
  flutter_screenutil: ^5.3.1
  html: ^0.15.0
  dio: ^4.0.4
  flutter_file_dialog: ^2.3.0
  
  
  flutter_colorpicker: ^1.0.3
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  carousel_slider: ^4.0.0
  archive: 

  

  fluttertoast: ^8.0.9
  flutter_native_splash: ^2.1.5
  store_checker: ^1.0.0
  badges: ^2.0.2
  marquee: ^2.2.2
  flutter_svg: ^1.0.3

  googleapis: ^8.1.0
  # # 아이폰 설정 필요 
  google_sign_in: ^5.3.1
  google_mobile_ads: ^1.2.0

  
  flutter_datetime_picker: 
   git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  drag_and_drop_lists: ^0.3.2+2
  
  
  google_mlkit_text_recognition:
    git:
      url: https://github.com/bharat-biradar/Google-Ml-Kit-plugin
      path: packages/google_mlkit_text_recognition

  pdf_text: 
    git:
      url: https://github.com/khjde1207/flutter-pdf-text
  scrollable_positioned_list: ^0.3.2
  disable_battery_optimization: ^1.1.0+1
  kss_dart: ^2.6.3
  perfect_volume_control: ^1.0.5


      
  
 

  
  

 
dev_dependencies: 
  flutter_test:
    sdk: flutter 
  integration_test: 
    sdk: flutter  
  flutter_oss_licenses: ^1.0.1 
  isar_generator: ^2.5.0
  build_runner: ^2.1.10

  # flutter_tesseract_ocr: 
  
   

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  #   - assets/tessdata/
  #   - test1.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic.otf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf

    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-Medium.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    
    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjo.otf
    
    - family: BMDOHYEON
      fonts:
        - asset: assets/fonts/BMDOHYEON_ttf.ttf
    
    - family: BMEULJIRO
      fonts:
        - asset: assets/fonts/BMEULJIROTTF.ttf

    - family: KoPubBatang
      fonts:
        - asset: assets/fonts/KoPubBatangLight.ttf
    
    - family: KoPubDotum
      fonts:
        - asset: assets/fonts/KoPubDotumLight.ttf

    - family: MaruBuri
      fonts:
        - asset: assets/fonts/MaruBuri-Regular.otf
        
    - family: NanumPen
      fonts:
        - asset: assets/fonts/NanumPen.otf
    
    - family: RIDIBatang
      fonts:
        - asset: assets/fonts/RIDIBatang.otf

    
    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
